version: "3"
services:
  fe:
    ports:
      - "4200:4200"
    environment:
      - "VUE_APP_API_URL=http://be:4300"
      - "PORT=4200"
      - "CYPRESS_API_URL=http://be:4300"
    command: sh -c "npm run serve"
  be:
    ports:
      - "4300:4300"
    environment:
      - "NODE_ENV=development"
      - "PORT=4300"
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm run dev"
