version: "3"
services:
  fe:
    image: node:latest
    depends_on:
      - be
    volumes:
      - ./fe:/app
    working_dir: /app
    command: sh -c "npm i && npm run serve"
  be:
    image: node:latest
    volumes:
      - ./be:/app
    working_dir: /app
    depends_on:
      - db
    command: sh -c "npm i && npx knex migrate:latest && npx knex seed:run && npm start"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
