version: "3"
services:
  fe:
    ports:
      - "8080:8080"
    environment:
      - "VUE_APP_API_URL=http://localhost:8081"
      - "PORT=8080"
      - "CYPRESS_API_URL=http://localhost:8081"
    command: sh -c "npm i && npm build && npm start"
    volumes:
      - dummy_fe:/code
  be:
    ports:
      - "8081:8081"
    environment:
      - "NODE_ENV=test"
      - "PORT=8081"
    volumes:
      - dummy_be:/code
