version: "3"
services:
  fe:
    expose:
      - "8080"
    environment:
      - "VUE_APP_API_URL=http://be:8081"
      - "PORT=8080"
      - "CYPRESS_API_URL=http://be:8081"
    command: sh -c "npm run build && npx http-server dist"
  be:
    expose:
      - "8081"
    environment:
      - "NODE_ENV=test"
      - "PORT=8081"
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"
  cypress:
    build: ./e2e
    volumes:
      - ./e2e/tests:/e2e/tests
    depends_on:
      - fe
      - be
      - db
    environment:
      - "PORT=8080"
      - "CYPRESS_baseUrl=http://fe:8080"
      - "CYPRESS_API_URL=http://be:8081"
