version: "3"
services:
  fe:
    build: ./fe
    depends_on:
      - be
    volumes:
      - ./fe:/app
  be:
    build: ./be
    volumes:
      - ./be:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
