version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Copy files over to temp containers
          command: |
            docker create -v /app --name dummy_fe node:latest /bin/true
            docker cp fe dummy_fe:/app
            docker create -v /app --name dummy_be node:latest /bin/true
            docker cp be dummy_be:/app
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Run backend unit tests
          command: |
            pwd
            ls -la
            docker-compose exec be sh -c "cd /app/be && npm test"
      - run:
          name: Run frontend unit tests
          command: |
            docker-compose exec be sh -c "cd /app/fe && npm test:unit"
      - run:
          name: Run frontend e2e tests
          command: |
            docker-compose exec be sh -c "cd /app/fe && npm test:e2e"
