version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run E2E tests
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d cypress
      - run:
          name: Run BE Unit tests
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d be sc -c "npm ci && npm test"
      - run:
          name: Run FE Unit tests
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d fe sh -c "npm ci && npm test:unit"
