version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start container
          command: |
            set -x
            docker-compose -p ci -f docker-compose.yml -f docker-compose.ci.yml up -d
      - run:
          name: Run backend unit tests
          command: |
            docker-compose run be sh -c "npm ci && npm test"
      - run:
          name: Run frontend unit tests
          command: |
            docker-compose run fe sh -c "npm ci && npm run test:unit"
      - run:
          name: Run frontend e2e tests
          command: |
            docker-compose run fe sh -c "npm ci && npm run test:e2e"
