version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.ci.yml up -d && docker-compose run cypress npx cypress run
