version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run container
          command: docker-compose -f docker-compose.ci.yml up -d
      - run:
          name: Run tests
          command: docker-compose run cypress npx cypress run
