version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            set -x
            docker-compose -p ci -f docker-compose.ci.yml up --build -d
            docker-compose run cypress npx cypress run
