version: 2
jobs:
  build:
    docker:
      - image: node:latest
        working_directory: /app
        steps:
          - checkout
          - run:
            name: Install Docker Compose
            command: |
              set -x
              curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
          - run:
            name: Start container and verify it is working
            command: |
              set -x
              docker-compose up -d
          - run:
            name: Run backend unit tests
            command: |
              cd be
              npm install
              npm test
          - run:
            name: Run frontend e2e tests
            command: |
              cd fe
              apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
              Xvfb :99 &
              export DISPLAY=:99
              npm install
              npm run build
              npm run test:unit
              cd dist
              PORT=8080 npm run test:ci
