version: 2
jobs:
  build:
    docker:
      - image: node:latest
        working_directory: /app
    steps:
      - checkout
      - run: cd fe && npm install
      - run: cd be && npm install
      - run: cd fe && npm run test:unit
      - run: cd fe && npm run serve:ci
      - run: cd be && npm run test:ci
