version: 2
jobs:
  build:
    docker:
      - image: node:latest
        working_directory: /app
    steps:
      - checkout
      - run: cd be && npm install
      - run: cd be && npm run test
      - run: cd fe && npm install
      - run: apt update && apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: Xvfb :99 &
      - run: export DISPLAY=:99
      - run: cd fe && npm run test:unit
      - run: cd fe && npm run serve:ci&
      - run: cd fe && npm run test:ci
      - run: pkill Xvfb
