version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d cypress
