version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose -p ci -f docker-compose.yml -f docker-compose.ci.yml up -d
      - run:
          name: Run backend unit tests
          command: |
            docker-compose exec be sh -c "pwd && ls -la"
            docker-compose exec be sh -c "npm i && npm test"
      - run:
          name: Run frontend unit tests
          command: |
            docker-compose exec be sh -c "npm test:unit"
      - run:
          name: Run frontend e2e tests
          command: |
            docker-compose exec be sh -c "npm test:e2e"
