version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: scripts/ci
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
