version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: scripts/ci
  deploy:
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-from-git

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
